import { describe, expect, it } from 'vitest';
import * as api from '../src/index.js';

/**
 * Contract test: freezes the runtime public API surface of
 * @bpmn-react/react. See core/tests/apiSurface.test.ts for rationale.
 */
const EXPECTED_EXPORTS = [
  'ARROW_MARKER_ID',
  'ARROW_MARKER_MUTED_ID',
  'ARROW_MARKER_SELECTED_ID',
  'BUILT_IN_PALETTE',
  'BUILT_IN_SHAPES',
  'BoundaryEventShape',
  'BpmnCanvas',
  'BpmnDesigner',
  'BpmnEditor',
  'BpmnViewer',
  'CanvasProvider',
  'ConnectedEdge',
  'ConnectedNode',
  'ConnectionPreview',
  'DataObjectShape',
  'DefaultShape',
  'Defs',
  'DiagramProvider',
  'DiffView',
  'EDGE_MARKER_CHEVRON_ID',
  'EDGE_MARKER_FILLED_ID',
  'EDGE_MARKER_OPEN_ID',
  'EdgeRenderer',
  'EditorConfigProvider',
  'EndEventShape',
  'EventBasedGatewayShape',
  'ExclusiveGatewayShape',
  'GridLayer',
  'GroupShape',
  'InclusiveGatewayShape',
  'IntermediateCatchEventShape',
  'IntermediateThrowEventShape',
  'LaneShape',
  'MAX_VIEWPORT_WIDTH',
  'MIN_VIEWPORT_WIDTH',
  'MiniMap',
  'NodeLabelEditor',
  'NodeRenderer',
  'Palette',
  'ParallelGatewayShape',
  'PoolShape',
  'PropertiesPanel',
  'ScriptTaskShape',
  'SelectionBoxOverlay',
  'ServiceTaskShape',
  'ShapeLabel',
  'StartEventShape',
  'StatusBadge',
  'SubProcessShape',
  'TaskShape',
  'TextAnnotationShape',
  'Toolbar',
  'UserTaskShape',
  'VersionTimeline',
  'applyWheelZoom',
  'createCanvasStore',
  'createStore',
  'downloadFile',
  'exportPng',
  'exportSvg',
  'fitViewport',
  'panViewport',
  'resolveEditorConfig',
  'screenToWorld',
  'svgToString',
  'theme',
  'useCanvasState',
  'useCanvasStore',
  'useDiagram',
  'useEditorConfig',
  'useInteractions',
  'useKeyboardShortcuts',
  'useStore',
  'wrapLabel',
  'zoomViewportAt',
].sort();

describe('@bpmn-react/react public API surface', () => {
  it('exports exactly the expected runtime members', () => {
    expect(Object.keys(api).sort()).toEqual(EXPECTED_EXPORTS);
  });

  it('every one of the 19 built-in shapes is registered in BUILT_IN_SHAPES', () => {
    expect(Object.keys(api.BUILT_IN_SHAPES).sort()).toEqual(
      [
        'boundaryEvent',
        'dataObject',
        'endEvent',
        'eventBasedGateway',
        'exclusiveGateway',
        'group',
        'inclusiveGateway',
        'intermediateCatchEvent',
        'intermediateThrowEvent',
        'lane',
        'parallelGateway',
        'pool',
        'scriptTask',
        'serviceTask',
        'startEvent',
        'subProcess',
        'task',
        'textAnnotation',
        'userTask',
      ].sort(),
    );
  });
});
