import { describe, expect, it } from 'vitest';
import * as api from '../src/index.js';

/**
 * Contract test: freezes the runtime public API surface of
 * @buildtovalue/react. See core/tests/apiSurface.test.ts for rationale.
 */
const EXPECTED_EXPORTS = [
  'ARROW_MARKER_ID',
  'ARROW_MARKER_MUTED_ID',
  'ARROW_MARKER_SELECTED_ID',
  'AUTOSAVE_DEBOUNCE_MS',
  'ShapeErrorBoundary',
  'autosaveKey',
  'clearAutosave',
  'readAutosave',
  'writeAutosave',
  'BUILT_IN_PALETTE',
  'BUILT_IN_PALETTE_GROUPS',
  'BUILT_IN_SHAPES',
  'BoundaryEventShape',
  'BpmnCanvas',
  'BpmnDesigner',
  'BpmnEditor',
  'BpmnSimulator',
  'BpmnReplay',
  'BpmnViewer',
  'ViewerCanvas',
  'BusinessRuleTaskShape',
  'GatewayChoiceCard',
  'SimulationOverlaySvg',
  'SimulationPanel',
  'ReplayOverlaySvg',
  'ReplayPanel',
  'diagramToReplayGraph',
  'formatDuration',
  'heatWidth',
  'useReplay',
  'edgeGeometryFor',
  'nodeCenter',
  'useSimulation',
  'CanvasProvider',
  'ConnectedEdge',
  'ConnectedNode',
  'CallActivityShape',
  'ConnectionPreview',
  'DataObjectShape',
  'DataStoreShape',
  'DefaultShape',
  'Defs',
  'DiagramProvider',
  'DiffView',
  'EdgePedigreeStrip',
  'EDGE_CORNER_RADIUS',
  'EDGE_MARKER_CHEVRON_ID',
  'CLOSED_HATCH_PATTERN_ID',
  'EDGE_MARKER_DISC_ID',
  'EDGE_MARKER_FILLED_ID',
  'EDGE_MARKER_OPEN_ID',
  'EdgeRenderer',
  'EmptyState',
  'EditorConfigProvider',
  'EndEventShape',
  'ComplexGatewayShape',
  'EventBasedGatewayShape',
  'ExclusiveGatewayShape',
  'GovernanceBreadcrumb',
  'GridLayer',
  'GroupShape',
  'InclusiveGatewayShape',
  'IntermediateCatchEventShape',
  'IntermediateThrowEventShape',
  'LaneShape',
  'LedgerStatus',
  'MAX_VIEWPORT_WIDTH',
  'MIN_VIEWPORT_WIDTH',
  'ManualTaskShape',
  'MiniMap',
  'NodeLabelEditor',
  'NodeRenderer',
  'Palette',
  'ParallelGatewayShape',
  'PoolShape',
  'PromotionPanel',
  'PropertiesPanel',
  'ReceiveTaskShape',
  'ScriptTaskShape',
  'SEAL_LABELS',
  'SignatureBadge',
  'CanonicalPayloadCard',
  'Cheatsheet',
  'CommandPalette',
  'AlignmentGuidesOverlay',
  'AnchorSeal',
  // Agent Lane (Handoff 12 A-4) — Agent Studio + isolated editor + shape.
  'AgentStudio',
  'AgentTaskShape',
  'addEdge',
  'addNode',
  'agentEditorReducer',
  'initEditorState',
  'layoutWorkflow',
  'nextNodeId',
  'proposeErrorBoundaryCommand',
  'removeNode',
  'toggleDecorator',
  'updateNodeConfig',
  'ANCHOR_GLYPHS',
  'ANCHOR_LABELS',
  'VERIFICATION_GLYPHS',
  'VERIFICATION_LABELS',
  'useAnchorCycle',
  'buildApprovalPayloadFor',
  // Handoff 15 §2e — canonical payload of the signed request-changes act.
  'buildChangeRequestPayloadFor',
  'buildGovernedExample',
  'builtinGlobalCommands',
  'builtinMenuItems',
  'pluginMenuItems',
  'pluginPadItems',
  'paletteEntries',
  'fuzzyScore',
  'SEMANTIC_ZOOM_MIN',
  'SHADOW_FILTER_ID',
  'SHADOW_HOVER_FILTER_ID',
  'SelectionBoxOverlay',
  'SendTaskShape',
  'ServiceTaskShape',
  'ShapeLabel',
  'StartEventShape',
  'StatusBadge',
  'SUBPROCESS_TITLE_HEIGHT',
  'SubProcessShape',
  'TaskShape',
  'TextAnnotationShape',
  'Toolbar',
  'UserTaskShape',
  'VersionBanner',
  'VersionTimeline',
  'applyWheelZoom',
  'createCanvasStore',
  'createStore',
  'downloadFile',
  'exportPng',
  'exportSvg',
  'fitViewport',
  'panViewport',
  'resolveEditorConfig',
  'screenToWorld',
  'svgToString',
  'theme',
  'useCanvasState',
  'useDismissal',
  'useCanvasStore',
  'useDiagram',
  'useEditorConfig',
  'useInteractions',
  'useKeyboardShortcuts',
  'KEYBOARD_SHORTCUT_CATALOG',
  'useStore',
  'wrapLabel',
  'zoomViewportAt',
  // Handoff 10 R-2a — named routers + inheritance routing.
  'NAMED_ROUTERS',
  'astarConnection',
  'roundedOrthogonalConnection',
  'straightRouter',
  'resolveRouter',
  'resolveEdgeRouterName',
  'edgeObstacles',
  'routedEdgeWaypoints',
  'routeEdge',
  // Handoff 10 R-2b — cached-waypoint routing + settle crossfade.
  'computeRoutedWaypoints',
  'deriveAstarRoutes',
  'rerouteConnectedEdges',
  'SearchPanel',
  // Handoff 14 §1d — lint problems dock (etiquette + engine, one surface),
  // plus the shared animated pan (search + lint use the SAME one).
  'LintPanel',
  'panViewportTo',
  'reducedMotion',
  // Handoff 15 §2a — review diff painted on the read-only viewer.
  'BpmnDiffViewer',
  // Handoff 15 §2c/§2d — host-injected review threads + approval gate.
  'createInMemoryReviewStore',
  'MIN_DISMISS_JUSTIFICATION',
  'reviewThreadsRule',
  // Handoff 14 §1e — auto-layout as a PROPOSAL (card + preview + crossfade).
  'LayoutProposalCard',
  'buildLayoutProposal',
  'LayoutPreviewOverlay',
  'LayoutSettleOverlay',
  'SearchPulseOverlay',
  'SettlingOverlay',
  'SETTLE_MS',
  // Handoff 10 R-3 — manual routes.
  'isManualEdge',
  'segmentIntersectsRect',
  'edgeRouteCollides',
  'translateManualWaypoints',
  'translateManualEdges',
  'backToAutoPatch',
  // Handoff 10 R-4 — clear routing + parallel corridors + label placement.
  'sideOfAnchor',
  'astarAutoEdgeIds',
  'routeAndSpread',
  'clearRoutingCommands',
  'longestSegmentMidpoint',
  // Handoff 9 CP-2 — governed copilot panel.
  'CopilotPanel',
  // Handoff 11 N-1 — boundary drag-to-attach snap highlight.
  'BoundarySnapOverlay',
  // F7 — reparent-on-drop container highlight.
  'ReparentTargetOverlay',
  // Handoff 11 N-3 — public event catalog + deprecation aliases.
  'EDITOR_EVENTS',
  'DEPRECATED_EVENT_ALIASES',
  // Handoff 11 N-5 — pluggable context menu + inline edge label editor.
  'ContextMenu',
  'EdgeLabelEditor',
  // Handoff 11 N-6 — injected i18n dictionary (engine + EN/PT_BR + hook).
  'translate',
  'mergeMessages',
  'I18nProvider',
  'useT',
  'EN',
  'PT_BR',
  // Optional off-thread compute (N-8).
  'createSyncExecutor',
  'createWorkerExecutor',
  'createWorkerHandler',
  'routeJob',
  'DEFAULT_JOBS',
].sort();

describe('@buildtovalue/react public API surface', () => {
  it('exports exactly the expected runtime members', () => {
    expect(Object.keys(api).sort()).toEqual(EXPECTED_EXPORTS);
  });

  it('every one of the 27 built-in shapes is registered in BUILT_IN_SHAPES', () => {
    expect(Object.keys(api.BUILT_IN_SHAPES).sort()).toEqual(
      [
        'agentTask',
        'boundaryEvent',
        'businessRuleTask',
        'callActivity',
        'dataObject',
        'dataStore',
        'endEvent',
        'complexGateway',
      'eventBasedGateway',
        'exclusiveGateway',
        'group',
        'inclusiveGateway',
        'intermediateCatchEvent',
        'intermediateThrowEvent',
        'lane',
        'manualTask',
        'parallelGateway',
        'pool',
        'receiveTask',
        'scriptTask',
        'sendTask',
        'serviceTask',
        'startEvent',
        'subProcess',
        'task',
        'textAnnotation',
        'userTask',
      ].sort(),
    );
  });
});
