import { describe, expect, it } from 'vitest';
import * as api from '../src/index.js';

/**
 * Contract test: freezes the *runtime* public API surface of
 * @buildtovalue/core (classes, functions, consts — type-only exports are
 * erased at compile time and never appear here, so type-level breaks are
 * caught separately by `tsc` in consuming packages).
 *
 * A failing diff here means an export was added, renamed, or removed.
 * Adding an export just requires updating EXPECTED_EXPORTS. Renaming or
 * removing one is a breaking change — bump the major/minor version
 * accordingly (see docs/versioning.md) before updating this fixture.
 */
const EXPECTED_EXPORTS = [
  'AuditLedger',
  'BPMNDI_NS',
  'BPMN_NS',
  'BUILT_IN_EDGE_TYPES',
  'BUILT_IN_NODE_TYPES',
  'ACTIVITY_MARKERS',
  'BUILT_IN_VALIDATION_RULES',
  'CONTAINER_NODE_TYPES',
  'BpmnAuditError',
  'BpmnError',
  'BpmnLifecycleError',
  'BpmnParseError',
  'BpmnRuleError',
  'BpmnValidationError',
  'BpmnXmlConverter',
  'CommandStack',
  'DC_NS',
  'DEFAULT_CLEARANCE',
  'DEFAULT_EXTENSION_NS',
  'DEFAULT_PORT_OFFSET',
  'DEFAULT_TRANSITIONS',
  'DI_NS',
  'DomXmlAdapter',
  'EventBus',
  'JsonSerializer',
  'LifecycleEngine',
  'MiniXmlAdapter',
  'MiniXmlParser',
  'NodeTypeRegistry',
  'RuleEngine',
  'ValidationEngine',
  'XmlBuilder',
  'activeEdges',
  'activeNodes',
  'activityMarkerOf',
  'addEdgeCommand',
  'addNodeCommand',
  // Agent Lane (Handoff 12 A-3) — agentTask helpers, autonomy→gate rule,
  // snapshot-fallback resolver.
  'agentAutonomyGateRule',
  'agentAutonomyLevelOf',
  'agentGateViolations',
  'agentTasksOf',
  'attachedBoundaryEventIds',
  'boundaryAttachedTo',
  // Handoff 11 N-1 — parametric boundary anchoring + atomic attach/detach.
  'BOUNDARY_SNAP_THRESHOLD',
  'boundaryAnchorOf',
  'boundaryNodePosition',
  'boundaryPositionOf',
  'nearestBoundaryAnchor',
  'attachBoundaryCommand',
  'detachBoundaryCommand',
  'boundaryEventHostRule',
  'bumpSemver',
  'canonicalJson',
  'canonicalJsonExact',
  // Flow classification shared by soundness/simulation (model/flow.ts).
  'NON_FLOW_TYPES',
  'NON_FLOW_EDGE_TYPES',
  'isFlowNode',
  'isFlowEdge',
  'flowScopeOf',
  // Layered auto-layout + align/distribute (referência item 2).
  'computeLayeredLayout',
  'alignPositions',
  'distributePositions',
  'childrenByLocalName',
  'clamp',
  'collapseWaypoints',
  'compositeCommand',
  'computeDiagramHash',
  // Handoff 16 E-1 (§3a) — named event definitions: helpers + undoable CRUD.
  'EVENT_DEFINITION_BUCKETS',
  'EVENT_DEFINITION_REF_KINDS',
  'addEventDefinitionCommand',
  'updateEventDefinitionCommand',
  'removeEventDefinitionCommand',
  'isEventDefinitionRemoval',
  'emptyEventDefinitions',
  'eventDefinitionsOf',
  'eventDefinitionList',
  'eventDefinitionRefOf',
  'eventDefinitionUsages',
  'findEventDefinition',
  'nextEventDefinitionId',
  // Handoff 18 §5d/§5e — shared escalation catch enumeration (lint + sim).
  'eligibleEscalationCatches',
  // Handoff 16 E-5 (§3d) — headless ISO 8601 timer parser + canonical prop.
  'parseTimerExpression',
  'timerPropertyOf',
  'computeDiff',
  // Handoff 15 V-1 — review-grade semantic diff (classified + stable order).
  'diffDiagrams',
  'edgeVersionDiff',
  'createDefaultRegistry',
  'createDefaultRuleEngine',
  'createDiagram',
  'createEdge',
  'createNode',
  'createSnapshot',
  'createVersion',
  'cubicBezierConnection',
  'cubicBezierPoint',
  'distance',
  'eventDefinitionOf',
  'escapeXmlAttribute',
  'escapeXmlText',
  'EVENT_DEFINITION_KINDS',
  'EVENT_NODE_TYPES',
  'eventFlowDirectionRule',
  'isEventType',
  'findByLocalName',
  'firstChildByLocalName',
  'generateId',
  'getAnchorPoint',
  'getAnchorSide',
  'getBoundingBox',
  'getDefaultXmlAdapter',
  'getEdgeChain',
  'isContainerType',
  'isEmptyDiff',
  'isNonInterrupting',
  // Handoff 17 ES-1 (§4a) — event subprocess: THE single-source predicates.
  'isEventSubprocess',
  'startIsInterrupting',
  'laneFlowNodeRefs',
  'localName',
  'missingStartEventRule',
  'moveNodeCommand',
  'normalizeForDiff',
  'nowIso',
  'orphanEdgeRule',
  'orthogonalConnection',
  'rectCenter',
  'rectContains',
  'rectsIntersect',
  'registerDefaultRules',
  'reachableGateFrom',
  'resolveAgentWorkflow',
  'removeEdgeCommand',
  'removeNodeCommand',
  'resizeNodeCommand',
  'restoreDiagramCommand',
  'nodeParentId',
  'childrenOf',
  'descendantIdsOf',
  'isSubProcessExpanded',
  'subProcessContainerAt',
  'calledElementOf',
  'computeEntryHash',
  'DATA_ASSOCIATION_EDGE_TYPE',
  'subProcessParentRule',
  'crossScopeEdgeRule',
  'roundCoord',
  'routeAStar',
  'routeOrthogonal',
  'selfConnectionRule',
  'sha256Hex',
  'snapToGrid',
  'straightConnection',
  'staleLaneRefRule',
  'supersedeEdgeCommand',
  'unknownTypeRule',
  'unreachableNodeRule',
  'updateEdgeCommand',
  'updateNodeCommand',
  'verifySnapshot',
  'waypointsToPath',
].sort();

describe('@buildtovalue/core public API surface', () => {
  it('exports exactly the expected runtime members', () => {
    expect(Object.keys(api).sort()).toEqual(EXPECTED_EXPORTS);
  });

  it('never exports undefined (catches a barrel re-export of a missing name)', () => {
    for (const key of Object.keys(api)) {
      expect(api[key as keyof typeof api], `export "${key}" is undefined`).not.toBeUndefined();
    }
  });
});
